### ISSUE TITLE
大佬，请教一下怎么合字体？

### ISSUE THREAD

**Issue by dajiba6** [georgealbert/.emacs.d#1]
照着网上教程https://blog.csdn.net/weixin_44441135/article/details/132320439合的字体输入中文还是会比英文高一截，中文上有一小段空白。但是用你合的字体无敌完美，请教一下。

**Comment by georgealbert** [comment]
和csdn里的步骤一样的啊。中英文是一个高度的。

以FantasqueSans Nerd Font和LXGW Mono Lite合并为例：
FantasqueSans Nerd Font的upm是2048，width是1060，宽度接近50%，非常适合和中文合并。
Fontforge合并步骤：
1. 用fontforge打开，“元素” -> “字体信息” -> “通用” -> “全字大小” ，把LXGW的upm从`1000`改为`2048`。
2. 和FantasqueSans Nerd Font合并。“元素” -> “合并字体”，选择中文字体LXGW。
4. 合并字体的行高(“元素” -> “字体信息” -> “OS/2” -> “尺寸” )不需要调整，用FantasqueSans的行高即可。如果要改，Win上高、字形上高和HHead上高最好一致，Win下深、字形下深和HHead下深最好绝对值一致。Typo行距和HHead行距为0。
5. “元素” -> “字体信息” -> “通用”，修改“下划线位置”position为`-200`、“高度”(fontforge的中文翻译错误，其实是thickness)为`30`。
7. 修改“PS字体名称”。
8. 使用width.py修改合并字体的width。从2048改为`2120`，就是英文字体宽度的2倍，不然无法中英文等宽。
9. 使用width.py修改合并字体的xAgvCharWidth。

也可以用`魔兽字体合并工具`步骤：
1. 把英文字体拖到工具
2. 把中文字体拖到工具
3. 使用width.py修改合并字体的width。从2048改为`2160`。
4. 使用width.py修改合并字体的xAgvCharWidth。

**Comment by dajiba6** [comment]
> 和csdn里的步骤一样的啊。中英文是一个高度的。
> 
> 以FantasqueSans Nerd Font和LXGW Mono Lite合并为例： FantasqueSans Nerd Font的upm是2048，width是1060，宽度接近50%，非常适合和中文合并。 Fontforge合并步骤：
> 
> 1. 用fontforge打开，“元素” -> “字体信息” -> “通用” -> “全字大小” ，把LXGW的upm从`1000`改为`2048`。
> 2. 和FantasqueSans Nerd Font合并。“元素” -> “合并字体”，选择中文字体LXGW。
> 3. 合并字体的行高(“元素” -> “字体信息” -> “OS/2” -> “尺寸” )不需要调整，用FantasqueSans的行高即可。如果要改，Win上高、字形上高和HHead上高最好一致，Win下深、字形下深和HHead下深最好绝对值一致。Typo行距和HHead行距为0。
> 4. “元素” -> “字体信息” -> “通用”，修改“下划线位置”position为`-200`、“高度”(fontforge的中文翻译错误，其实是thickness)为`30`。
> 5. 修改“PS字体名称”。
> 6. 使用width.py修改合并字体的width。从2048改为`2120`，就是英文字体宽度的2倍，不然无法中英文等宽。
> 7. 使用width.py修改合并字体的xAgvCharWidth。
> 
> 也可以用`魔兽字体合并工具`步骤：
> 
> 1. 把英文字体拖到工具
> 2. 把中文字体拖到工具
> 3. 使用width.py修改合并字体的width。从2048改为`2160`。
> 4. 使用width.py修改合并字体的xAgvCharWidth。

用魔兽字体合并很方便，合了Jetbrains和更纱黑，在ubuntu中可以正常使用，但是放到mac中就无法识别，请问您有碰到过这种情况吗？

**Comment by georgealbert** [comment]
无法识别是什么意思？双击字体文件能打开字体册吗？

BTW：没钱fq，直接上的github，有时候打不开，哈哈。

**Comment by dajiba6** [comment]
> 无法识别是什么意思？双击字体文件能打开字体册吗？
> 
> BTW：没钱fq，直接上的github，有时候打不开，哈哈。

能打开，但是第一次点直接没有读取的流程。
第二次再点，显示已经安装过了，install是灰色的。
在library/fonts中能找到这个ttf文件，但是在字体册->我的字体中没有这个字体

**Comment by dajiba6** [comment]
没钱too，跟朋友一起拼团fq，一年40块

**Comment by georgealbert** [comment]
不知道了。我也是macOS，没有遇到过这个问题。你在我的MyNerdFonts的repo可以找到很多带“+”号的字体文件，都是魔兽字体合并工具合并的，可以试试能不能打开。

**Comment by dajiba6** [comment]
> 不知道了。我也是macOS，没有遇到过这个问题。你在我的MyNerdFonts的repo可以找到很多带“+”号的字体文件，都是魔兽字体合并工具合并的，可以试试能不能打开。

解决了，电脑重启就ok了
